application:
  title: 至轻云
  website: https://zhiqingyun.isxcode.com
  describe: 打造超轻量级批处理大数据平台

server:
  tomcat:
    connection-timeout: 120s

spring:

  profiles:
    active: local

  security:
    user:
      roles: ADMIN

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  banner:
    location: classpath:banner/logo.txt

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 200
      min-idle: 10
      max-wait: 30000
      test-while-idle: true
      filters: stat,wall,log4j2
      validationQuery: select 'x'
      stat-view-servlet:
        enabled: true

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.isxcode.star.config.JpaTableUpperCaseStrategy
    properties:
      hibernate:
        session_factory:
          statement_inspector: com.isxcode.star.config.JpaTenantInterceptor

  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  quartz:
    scheduler-name: spark-yun-quartz-scheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

  cache:
    type: simple

  thymeleaf:
    check-template-location: false

  api-docs:
    path: /swagger-ui/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.isxcode.star

isx-app:
  admin-url:
    - /swagger-ui/** # http://localhost:8080/swagger-ui/index.html
    - /h2-console/** # http://localhost:8080/h2-console
    - /druid/** # http://localhost:8080/druid/index.html
  anonymous-url:
    - / # 让页面可以访问前端
    - /static/** # 放行前端资源文件
    - /favicon.ico # 放行网站的logo
    - /login # 放行登录接口
    - /**/open/** # 放行所有的开放接口
    - /**/api/** # 放行所有自定义接口
    - /**/api/**/** # 放行所有自定义接口
    - /**/api/**/**/** # 放行所有自定义接口
    - /home/** # 放行全部前端的刷新访问路径