spark-yun:
  agent-tar-gz-dir: /spark-yun
  agent-bin-dir: /spark-yun/bin
  default-agent-port: 30177

spring:

  # 数据源配置 http://localhost:8080/h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/h2/data
    username: root
    password: ispong123
